apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mdb
spec:
  generators:
    - git:
        repoURL: https://github.com/marinkobabic/argocd.git
        revision: test
        files:
          - path: "environments/**/config.yaml"
  template:
    metadata:
      name: '{{path[3]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/marinkobabic/argocd.git
        targetRevision: test
        path: 'charts/ingress-nginx/3.10.1'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'in-cluster'
        namespace: 'mdb'
      syncPolicy:
        automated: {}