apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mdb
spec:
  generators:
    - git:
        repoURL: https://github.com/marinkobabic/argocd.git
        revision: master
        files:
          - path: "environments/**/config.yaml"
  template:
    metadata:
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/marinkobabic/argocd.git
        targetRevision: master
        path: 'charts/{{version}}/{{path.basename}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
      destination:
        name: '{{path[1]}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        automated: {}