apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dban
spec:
  generators:
    - git:
        repoURL: https://bitbucket.ebs.crealogix.net:8443/scm/~mbab/dban-argocd-deployment.git
        revision: config
        files:
          - path: "environments/**/config.yaml"
  template:
    metadata:
      name: '{{path[3]}}'
    spec:
      project: dban
      source:
        repoURL: https://bitbucket.ebs.crealogix.net:8443/scm/~mbab/dban-argocd-deployment.git
        targetRevision: HEAD
        path: 'charts/{{version}}/path[3]'
        helm:
          valueFiles:
            - values.yaml
            - environments/{{path[0]}}/values.yaml
            - environments/{{path[0]}}/{{path[1]}}/values.yaml
            - environments/{{path[0]}}/{{path[1]}}/{{path[2]}}/values.yaml
      destination:
        server: '{{path[1]}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        automated: {}