apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mdb
spec:
  generators:
    - git:
        repoURL: https://github.com/marinkobabic/argocd.git
        revision: master
        files:
          - path: "environments/**/config.yaml"
  template:
    metadata:
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/marinkobabic/argocd.git
        targetRevision: master
        path: 'charts/{{path.basename}}/{{version}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - environments/{{path[0]}}/values.yaml
            - environments/{{path[0]}}/{{path[1]}}/values.yaml
            - environments/{{path[0]}}/{{path[1]}}/{{path[2]}}/values.yaml
      destination:
        name: '{{path[1]}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        automated: {}